export const LANGUAGES = [
  ['en', 'English'],
  ['zh', '简体中文']
];
export function local() {
  return localStorage.getItem('lang') ?? 'en';
}
export function L(k, opt) {
  let loc = local();
  let prop = lang[local()][k];
  return typeof prop == 'function' ? prop(opt) : prop;
}
export const lang = {
  en: {
    //setting:
    language: 'Language',
    color_mode: 'Color Mode',
    COLOR_MODES: [['s', 'System'], ['l', 'Light'], ['d', 'Dark']],
    your_nick: 'Your nick name',
    new_nick: 'New nick name',
    web_notify: 'Web Notification',
    lock: 'Lock',
    unlock: 'Unlock',
    set_lock_pin: 'Set lock PIN',
    input_required: 'Empty input, this filed is required.',
    set: 'Save',
    clear: 'Clear',
    enable: 'Enable',
    not_support: 'Not Supported',
    done: 'Done',
    privacy: 'Privacy',
    clear_chat: 'Clear All Chats',
    clear_chat_confirm: 'All chats history will be erased, Continue?',
    expire_invitation: 'Expire all chat invitations',
    expire_invitation_confirm: 'All chat invitations will be expired, Continue?',
    //navigator:
    site_tit: 'Chànà - क्षण',
    site_sub_tit: 'Anonymous Encrypted Chat',
    invitation: 'Invitation',
    chat: 'Chat',
    setting: 'Setting',
    //chat:
    send: 'Send',
    slt_img: 'Select image(s)',
    slt_file: 'Select file(s)',
    img: o =>`${o.num} image(s) selected`,
    file: o =>`${o.num} file(s) selected`,
    media_not_support: 'Oopts, Media device not supported.',
    no_chat_tip: `You need <a href='/' class='navi'>invite</a> someone to start a chat.`,
    ws_rec: 'Try to connect the server...',
    ws_rec_fail: 'Fail to connect. Refresh the page to start over',
    offline: o => `${o.nick} is offline, message(s) will be delivered when user is online.`,
    //invitation:
    send_inv: 'I want to invite someone to chat',
    recv_inv: 'I received a chat invitation',
    lnk_copied: 'Invitation link has copied to clipboard.',
    inv_lnk: 'Copy & Share this invitation',
    share: 'Create',
    share_inv_tip: 'chat invitation to your contact',
    open_inv_tip: 'Paste invitation link here',
    invalid_inv_lnk: 'Invalid Invitation Link.',
    inv_tit: 'Private Chat Invitation',
    inv_txt: 'From: <Chànà - क्षण - Anonymous Encrypted Chat>',
    accept: 'Accept',
    decline: 'Decline',
    inv_cancel: 'Cancel Chat',
    inv_used: 'This one-time invitation has been used.',
    inv_self: 'Sorry, you cannot invite yourself.',
    inv_cancel_confirm: 'If cancel this chat，re-invitation is required to reach each other, continue？',
    share_tit: '~ Anonymous Private Chat Invitation ~',
    share_body: o => `You are invited to start a private chat with <${o.nick}>.`,
    inv_track_s5: o => `Waiting for <${o.nick}> to join this private chat.`,
    //command:
    cmd_remark: 'set a alias for current chat',
    cmd_clear: 'Clear history of current chat',
    cmd_leave: 'Leave the current chat',
    cmd_exit: 'Exit the current chat after clearing history',
  },
  zh: {
    //setting:
    language: '语言',
    color_mode: '颜色模式',
    COLOR_MODES: [['s', '系统'], ['l', '浅色'], ['d', '深色']],
    your_nick: '您的昵称',
    new_nick: '新昵称',
    web_notify: '网页通知',
    lock: '锁定',
    unlock: '解锁',
    set_lock_pin: '设置锁定PIN码',
    input_required: '输入为空, 请重新输入。',
    set: '保存',
    clear: '清除',
    enable: '启用',
    not_support: '不支持',
    done: '完成',
    privacy: '隐私',
    clear_chat: '清除聊天数据',
    clear_chat_confirm: '所有的聊天历史都将被删除，是否继续？',
    expire_invitation: '过期所有的聊天邀请',
    expire_invitation_confirm: '所有的聊天邀请都将失效，是否继续？',
    //navigator
    site_tit: '刹那 - क्षण',
    site_sub_tit: '匿名加密聊天',
    invitation: '邀请',
    chat: '聊天',
    setting: '设置',
    //chat:
    send: '发送',
    slt_img: '选择图片',
    slt_file: '选择文件',
    img: o =>`已选择${o.num}张图片`,
    file: o =>`已选择${o.num}份文件`,
    media_not_support: '媒体设备不支持此功能',
    no_chat_tip: `请 <a href='/' class='navi'>邀请</a> 某人以开启聊天.`,
    ws_rec: '服务器连接中...',
    ws_rec_fail: '无法连接, 请刷新页面重试.',
    offline: o => `${o.nick} 已离线, 离线消息会在用户上线后重新发送.`,
    //invitation:
    send_inv: '我想邀请某人聊天',
    recv_inv: '我收到一封聊天邀请',
    lnk_copied: '邀请链接已复制到剪贴板.',
    inv_lnk: '复制并分享此邀请链接',
    share: '创建',
    share_inv_tip: '您的聊天邀请',
    open_inv_tip: '在此粘贴聊天邀请',
    invalid_inv_lnk: '无效的邀请链接.',
    inv_tit: '聊天邀请',
    inv_txt: '来自：<刹那(Chànà) - 匿名加密聊天App>',
    accept: '接受',
    decline: '拒绝',
    inv_cancel: '取消聊天',
    inv_used: '邀请链接是一次性的，且已经使用过.',
    inv_self: '对不起, 您不能邀请自己.',
    inv_cancel_confirm: '取消此次聊天，下次聊天需重新邀请，是否继续？',
    share_tit: '~ 匿名加密聊天邀请 ~',
    share_body: o => `您收到来自<${o.nick}>的私聊邀请.`,
    inv_track_s5: o => `等待<${o.nick}>上线后开启聊天.`,
    //command:
    cmd_remark: '为当前聊天设置别名',
    cmd_clear: '清除当前聊天的历史',
    cmd_leave: '离开当前聊天',
    cmd_exit: '离开当前聊天并删除历史',
    cmd_help: '使用说明',
  }
};
